### ISSUE TITLE
device: should be object (#/properties/data/type)

### ISSUE THREAD

**Issue by robkor** [HobbyEd/io.maxem.app#1]
I have installed this app v0.4.0 on my Homey Pro (v3.2.0), but I cannot get it to work.

I can install the app and enter and save the user data from my Maxem account.
When adding/installing the Maxem.io device, the serial number of my Maxem box is shown with a blue tick next to it, if I then choose Next I get an error message: _device: should be object (#/properties/data/type)_. The device was not added.

Can you please correct this issue and post a new release on Homey?

**Comment by HobbyEd** [comment]
Thanks for reporting. Issues is solved in version 0.47
